spring.application.name=demo
#spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.datasource.url=jdbc:mariadb://54.180.229.47:3307/tutor
spring.datasource.username=tutor
spring.datasource.password=tutorp
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.vectorstore.mariadb.initialize-schema=true

