spring.application.name=demo

spring.datasource.url=jdbc:mysql://54.180.229.47:3306/tutor
spring.datasource.username=tutor
spring.datasource.password=tutorp

mybatis.mapper-locations=classpath:mapper/*.xml